### ISSUE TITLE
Basic examples

### ISSUE THREAD

**Issue by Spoiledpay** [brombres/Rogue#98]
Great initiative in creating the development language. There are some examples to be shown such as Strings, Array, For, Else, Loop. And any function that uses Windows GUI?

**Comment by brombres** [comment]
There's a comprehensive [syntax guide](https://github.com/brombres/Rogue/wiki/Syntax) on the [wiki](https://github.com/brombres/Rogue/wiki). I've also just now added [API documentation](https://github.com/brombres/Rogue/wiki/API) to the wiki and linked to the wiki from the main README.

I'll add more examples and improve the API documentation over time. Feel free to DM me ( @brombres on X ) with other questions in the meantime.

I'll answer the Windows GUI question on #99.
